
export{ default as css3 } from './techs/css3.svg'
export { default as express } from './techs/express.svg'
export { default as figma } from './techs/figma.svg'
export { default as graphql } from './techs/graphql.svg'
export { default as html5 } from './techs/html5.svg'
export { default as jira } from './techs/jira.svg'
export { default as mongodb } from './techs/mongodb.svg'
export { default as mongoose } from './techs/mongoose.svg'
export { default as nextjs } from './techs/nextjs.svg'
export { default as nodejs } from './techs/nodejs.svg'
export { default as reactjs } from './techs/reactjs.svg'
export { default as sequelize } from './techs/sequelize.svg'
export { default as sql } from './techs/sql.svg'
export { default as swagger } from './techs/swagger.svg'
export { default as trello } from './techs/trello.svg'
export { default as typescript } from './techs/typescript.svg'
export { default as vite } from './techs/vite.svg'
export { default as github } from './social/github.svg'
export { default as gmail } from './social/gmail.svg'
export { default as linkedin } from './social/linkedin.svg'
export { default as whatsapp } from './social/whatsapp.svg'